apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app-argocd
  template:
    metadata:
      labels:
        app: product-app-argocd
    spec:
      containers:
      - name: product-app-argocd
        image: devjor/product-app:02
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/productDB"
        - name: NODE_OPTIONS
          value: "--max-old-space-size=512"  # Set max heap size to 512MB
        resources:
          limits:
            memory: "1Gi"  # Increased memory limit
            cpu: "500m"
          requests:
            memory: "512Mi"  # Increased memory request
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: product-app-argocd-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: product-app-argocd
